In [1]:
#!pip install opencv-python

# open image

In [1]:
import cv2

In [2]:
print(cv2.__version__)

4.5.3


In [3]:
img=cv2.imread('download.jfif',0)

In [4]:
print(img)

[[246 246 246 ... 234 234 234]
 [246 246 246 ... 234 234 234]
 [246 246 246 ... 234 234 234]
 ...
 [246 246 246 ... 237 237 237]
 [246 246 246 ... 237 237 237]
 [246 246 246 ... 237 237 237]]


In [5]:
cv2.imshow('show image',img)

In [6]:
k=cv2.waitKey(0)
if k==27:
    cv2.destroyAllWindows()

In [8]:
#/////////////////////////////////////////////////// vidoe

# open vidow

In [39]:
import cv2
import datetime
cap=cv2.VideoCapture(0)
fourcc=cv2.VideoWriter_fourcc(*'XVID')
outi=cv2.VideoWriter('outi.avi',fourcc,20.0,(640,480))

In [40]:
print(cap.isOpened())

True


In [41]:
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
        
    print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    #frame=cv2.flip(frame,0)
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    outi.write(frame)  
    cv2.imshow('frame',gray)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
outi.release()
cv2.destroyAllWindows()


640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.

In [7]:
pwd

'E:\\مجالى\\computer vision\\111111'

In [8]:
#/////////////////////////////////

In [9]:
#draw shapes on images

In [10]:
import numpy as np

In [11]:
import cv2

In [12]:
img=np.zeros([512,512,3],np.uint8)
#img=cv2.line(img,(0,0),(256,256),(0,0,255),5)
#img=cv2.arrowedLine(img,(0,255),(256,256),(0,0,255),5)
#img=cv2.rectangle(img,(384,0),(510,128),(255,0,0),20)
#img=cv2.circle(img,(256,256),63,(0,255,0),20)
#font=cv2.FONT_HERSHEY_COMPLEX
#img=cv2.putText(img,'ahmed',(10,100),font,4,(0,255,255),10)
pts=np.array([[50,50],[100,80],[100,160],[200,100]],np.int32)
img=cv2.polylines(img,[pts],True,(0,255,255))
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
img

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

# set width , height

In [14]:
import cv2
cap=cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
cap.set(3,10000)
cap.set(4,10000)

print(cap.get(3))
print(cap.get(4))
while cap.isOpened():
    ret,frame=cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv2.imshow('frame', gray)
    if cv2.waitKey(1) == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

640.0
480.0
1280.0
720.0


# data time

In [19]:
import cv2
import datetime

In [20]:
import cv2
cap=cv2.VideoCapture(0)
fourcc=cv2.VideoWriter_fourcc(*'XVID')
out=cv2.VideoWriter('out.avi',fourcc,20.0,(640,480))

In [21]:
print(cap.isOpened())

True


In [22]:
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
        
    print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    #frame=cv2.flip(frame,0)
    font=cv2.FONT_HERSHEY_SIMPLEX
    text='width: '+str(cap.get(3))+' height: '+str(cap.get(4))
    date=str(datetime.datetime.now())
    frame=cv2.putText(frame,text,(10,100),font,1,(0,255,255),2)
    frame=cv2.putText(frame,date,(10,450),font,1,(0,255,255),2)
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    out.write(frame)  
    cv2.imshow('frame',frame)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
out.release()
cv2.destroyAllWindows()

640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.

In [42]:
pwd

'E:\\مجالى\\computer vision\\111111'

# mouse events

In [15]:
import numpy as np
import cv2

In [16]:
ev=[i for i in dir(cv2) if 'EVENT' in i]
print (ev)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [19]:
def click(ev,x,y,flags,param):
        if ev==cv2.EVENT_LBUTTONDOWN:
                print(x,' , ',y)
                font=cv2.FONT_HERSHEY_SIMPLEX
                strxy=str(x)+' , '+str(y)
                cv2.putText(img,strxy,(x,y),font, .5,(255,255,0),2)
                cv2.imshow('image',img)
        if ev==cv2.EVENT_RBUTTONDOWN:
                blue=img[y,x,0]
                green=img[y,x,1]
                red=img[y,x,2]
                font=cv2.FONT_HERSHEY_SIMPLEX 
                strBGR='[ '+str(blue)+' , '+str(green)+' , '+str(red)+' ]'
                cv2.putText(img,strBGR,(x,y),font, .5,(0,245,255),2)
                cv2.imshow('image',img)



In [21]:
img=cv2.imread('unnamed.jpg')
cv2.imshow('image',img)

cv2.setMouseCallback('image',click)

cv2.waitKey(0)
cv2.destroyAllWindows()

272  ,  19
317  ,  170
125  ,  216
49  ,  127
37  ,  207
33  ,  261
404  ,  279
